FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy prisma schema and generate client
COPY prisma ./prisma/
RUN npx prisma generate

# Copy app source
COPY . .

# Expose port and start dev server
EXPOSE 5001
CMD npx prisma migrate deploy && npm run dev
